

[build]
  functions = ".netlify/funciones"
  publish = "."

[functions]
  directory = ".netlify/funciones"
  node_bundler = "nft"

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Para manejar CORS y archivos estáticos
[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"